// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  translation: {
    language: {
      en: "English";
      label: "界面语言";
      system: "跟随系统";
      zhCN: "简体中文";
    };
    navigation: {
      home: "主页";
      knowledge: "知识库";
      settings: "设置";
    };
    notFound: {
      description: "你访问的页面可能已被移动、删除，或地址输入有误。";
      returnHome: "返回首页";
      title: "没有找到这个页面";
    };
    sidebar: {
      description: "显示移动端侧边栏。";
      title: "侧边栏";
      toggle: "切换侧边栏";
    };
    theme: {
      dark: "深色";
      label: "外观";
      light: "浅色";
      system: "跟随系统";
    };
  };
}
